# _config.yml

title: Deployable technology for scalable transportation
author: Zhiyao Zhang
email: zhiyao.zhang@vanderbilt.edu

# Use the default Jekyll theme
theme: minima

# Navigation pages
header_pages:
  - index.md
  - research.md
  - blogs.md

# You can add your social media links here
google_scholar_username: rVEhUBgAAAAJ&hl=en
github_username:  RealZYZhang
linkedin_username: zhiyao-zhang

# Disable RSS feed
rss: false

# Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock