# _config.yml

title: Zhiyao Zhang
author: Deployable technology for scalable transportation
email: zhiyao.zhang@vanderbilt.edu

# Use the default Jekyll theme
# theme: minima
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# Navigation pages
header_pages:
  - index.md
  - research.md
  - blogs.md

# You can add your social media links here
google_scholar_username: rVEhUBgAAAAJ&hl=en
github_username:  RealZYZhang
linkedin_username: zhiyao-zhang

# Search
search: true

# Disable RSS feed
rss: false

# Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock